-- Database: DeliverySys

CREATE TABLE Zip
(zipcode INTEGER PRIMARY KEY NOT NULL,
 city VARCHAR(20) NOT NULL,
 state VARCHAR(20) NOT NULL);

CREATE TABLE Customer
(customerId INTEGER PRIMARY KEY NOT NULL,
 customerName VARCHAR(40) NOT NULL,
 customerEmail VARCHAR(40) UNIQUE NOT NULL,
 customerPassword VARCHAR(40) NOT NULL,
 customerAddress1 VARCHAR(40) NOT NULL,
 customerAddress2 VARCHAR(40),
 zipcode INTEGER NOT NULL,
 customerPhone BIGINT NOT NULL,
 rewardPoints INTEGER DEFAULT 0,
 CONSTRAINT ZIP_FK FOREIGN KEY (zipcode) REFERENCES Zip (zipcode) ON DELETE NO ACTION);

 CREATE TABLE Vendor
(vendorId INTEGER PRIMARY KEY NOT NULL,
 vendorName VARCHAR(20) NOT NULL,
 vendorEmail VARCHAR(40) UNIQUE NOT NULL,
 vendorPassword VARCHAR(40) NOT NULL,
 vendorAddress1 VARCHAR(40) NOT NULL,
 vendorAddress2 VARCHAR(40),
 zipcode INTEGER NOT NULL,
 vendorPhone BIGINT NOT NULL,
 cuisine VARCHAR(20),
 businessType VARCHAR(20) NOT NULL CHECK(businessType IN ('Restaurant','Home based')),
 CONSTRAINT ZIP_FK FOREIGN KEY (zipcode) REFERENCES Zip (zipcode) ON DELETE NO ACTION);

 CREATE TABLE Driver
(driverId INTEGER PRIMARY KEY NOT NULL,
 driverName VARCHAR(40) NOT NULL,
 driverEmail VARCHAR(40) UNIQUE NOT NULL,
 driverPhone BIGINT NOT NULL,
 driverVehicle VARCHAR(40) NOT NULL,
 vendorId INTEGER NOT NULL,
 CONSTRAINT VENDOR_FK FOREIGN KEY (vendorId) REFERENCES Vendor (vendorId) ON DELETE CASCADE);

CREATE TABLE Menu
(dishId INTEGER PRIMARY KEY NOT NULL,
 dishStatus BOOLEAN NOT NULL,
 vendorId INTEGER NOT NULL,
 dishName VARCHAR(40) NOT NULL,
 dishPrice NUMERIC(7,2) NOT NULL,
 CONSTRAINT VENDOR_FK FOREIGN KEY (vendorId) REFERENCES Vendor (vendorId) ON DELETE CASCADE);

CREATE TABLE Orders
(orderId INTEGER PRIMARY KEY NOT NULL,
 customerId INTEGER NOT NULL,
 vendorId INTEGER NOT NULL,
 dateCreated DATE DEFAULT CURRENT_TIMESTAMP,
 orderTotal NUMERIC(7,2) NOT NULL,
 driverId INTEGER NULL,
 deliveryType VARCHAR(20) NOT NULL,
 orderStatus VARCHAR(20) NOT NULL,
 CONSTRAINT CUSTOMER_FK FOREIGN KEY (customerId) REFERENCES Customer (customerId) ON DELETE NO ACTION,
 CONSTRAINT VENDOR_FK FOREIGN KEY (vendorId) REFERENCES Vendor (vendorId) ON DELETE CASCADE,
 CONSTRAINT DRIVER_FK FOREIGN KEY (driverID) REFERENCES Driver (driverId) ON DELETE SET NULL);

CREATE TABLE OrderDetails
(orderId INTEGER NOT NULL,
 dishId INTEGER NOT NULL,
 quantity NUMERIC(4,0) NOT NULL,
 amount NUMERIC(5,2) NOT NULL,
 PRIMARY KEY (orderId, dishId),
 CONSTRAINT ORDERS_FK FOREIGN KEY (orderId) REFERENCES Orders (orderId) ON DELETE CASCADE,
 CONSTRAINT MENU_FK FOREIGN KEY (dishId) REFERENCES Menu (dishId) ON DELETE NO ACTION);
